
permalink: /:categories/:title
markdown: kramdown

exclude: [
    ".rvmrc",
    ".rbenv-version",
    "README.md",
    "Rakefile",
    "changelog.md",
    "node_modules",
    "gulpfile.js",
    ".editorconfig",
    "assets/components/*"
]

title : "The Listen Ship Repeat Podcast"
email: hello@listenshiprepeat.com
description: "Listen Ship Repeat is a weekly podcast about the inner workings of startups and how to build them. It is performed by two veteran founders and web developers who have worked closely with many startups over the course of a decade and beyond."
author :
  name : "Listen Ship Repeat"
  email : "hello@listenshiprepeat.com"
  # feedburner : feedname

githubrepo: "https://github.com/thanpolas/listenshiprepeat.com"

production_url : http://listenshiprepeat.com

# Open Graph data
og:
  app_id: "xxx"
  title: "The Listen Ship Repeat Podcast"
  site_name: "Listen Ship Repeat"
  image: "http://skgtech.io/assets/img/skgtech-social-logo.png"

# Google Analytics
analytics :
  provider : google
  google :
    tracking_id : 'UA-xxx-3'
    domain: 'listenshiprepeat.com'
